In [1]:
#!pip3 install tensorflow
import tensorflow as tf

# Tensor Video 2.3

# Tensor

In [2]:
a = tf.constant([[1.0, 2.0], [3.0, 4.0]])
a

<tf.Tensor 'Const:0' shape=(2, 2) dtype=float32>

In [3]:
sess = tf.Session()
sess.run(a)

array([[ 1.,  2.],
       [ 3.,  4.]], dtype=float32)

# Rank

In [7]:
#Rank of previous example
sess.run(tf.rank(a))

2

### Rank 0

In [8]:
mammal = tf.Variable("Elephant", tf.string)
ignition = tf.Variable(451, tf.int16)
floating = tf.Variable(3.14159265359, tf.float64)
its_complicated = tf.Variable((12.3, -4.85), tf.complex64)


For a rank 0 tensor (a scalar), no indices are necessary, since it is already a single number.

### Rank 1

In [9]:
mystr = tf.Variable(["Hello"], tf.string)
cool_numbers  = tf.Variable([3.14159, 2.71828], tf.float32)
first_primes = tf.Variable([2, 3, 5, 7, 11], tf.int32)
its_very_complicated = tf.Variable([(12.3, -4.85), (7.5, -6.23)], tf.complex64)

### For a rank 1 tensor (a vector), passing a single index allows you to access a number:

In case of image processing

### Confusion with many aspirants while understanding rank

In [16]:
my_image = tf.zeros([10, 299, 299, 3])  # batch x height x width x color

# What should be the rank 1 or 4?

## Getting a tf.Tensor object's rank

In [17]:
r = tf.rank(my_image)
sess.run(r)

### using indexes

For a rank 0 tensor (a scalar), no indices are necessary, since it is already a single number.

For a rank 1 tensor (a vector), passing a single index allows you to access a number:


In [26]:
my_scalar = my_image[2,1]

In [27]:
my_scalar

<tf.Tensor 'strided_slice_5:0' shape=(299, 3) dtype=float32>

In [63]:
#For tensors of rank 2 or higher, the situation is more interesting. 
#For a tf.Tensor of rank 2, passing two numbers returns a scalar, as expected:

my_scalar = my_image[1, 2, 3,2]
print(my_scalar)

#Passing a single number, however, returns a subvector of a matrix, as follows:

my_row_vector = my_image[1,1,2]
print(my_row_vector)

##You might encounter the way of column slicing as below but avoid using it unless you are comfortable
my_column_vector = my_image[:, 298]
print(my_column_vector)

#The : notation is python slicing syntax for "leave this dimension alone". This is useful in higher-rank Tensors, 
#as it allows you to access its subvectors, submatrices, and even other subtensors.

Tensor("strided_slice_35:0", shape=(), dtype=float32)
Tensor("strided_slice_36:0", shape=(3,), dtype=float32)
Tensor("strided_slice_37:0", shape=(10, 299, 3), dtype=float32)


### Alternative specialized way to slicing

In [39]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]],
                 [[3, 3, 3], [4, 4, 4]],
                 [[5, 5, 5], [6, 6, 6]]])


In [61]:
sess.run(tf.slice(t,begin=[1,0,0],size=[1,2,2]))

array([[[3, 3],
        [4, 4]]], dtype=int32)

# Shape

In [65]:
rank_three_tensor = tf.ones([3, 4, 5])
matrix = tf.reshape(rank_three_tensor, [6, 10])  # Reshape existing content into
                                                 # a 6x10 matrix
matrixB = tf.reshape(matrix, [3, -1])  #  Reshape existing content into a 3x20
                                       # matrix. -1 tells reshape to calculate
                                       # the size of this dimension.
matrixAlt = tf.reshape(matrixB, [4, 3, -1])  # Reshape existing content into a
                                             #4x3x5 tensor

# Note that the number of elements of the reshaped Tensors has to match the
# original number of elements. Therefore, the following example generates an
# error because no possible value for the last dimension will match the number
# of elements.



In [67]:
#yet_another = tf.reshape(matrixAlt, [13, 2, -1])  # ERROR!

# Data types
### To inspect a tf.Tensor's data type use the Tensor.dtype property.

In [78]:
# Cast a constant integer tensor into floating point.
int_tensor = tf.constant([1, 2, 3], dtype=tf.int32)
print(int_tensor)
float_tensor = tf.cast(int_tensor, dtype=tf.float32)
print(float_tensor)

Tensor("Const_12:0", shape=(3,), dtype=int32)
Tensor("Cast_10:0", shape=(3,), dtype=float32)


# Tensorflow constants

In [82]:
# Constant 1-D Tensor populated with value list.
tensor1 = tf.constant([1, 2, 3, 4, 5, 6, 7]) #   [1 2 3 4 5 6 7]
print(sess.run(tensor1))
# Constant 2-D tensor populated with scalar value -1.
tensor2 = tf.constant(-1.0, shape=[2, 3]) # [[-1. -1. -1.],[-1. -1. -1.]]
print(sess.run(tensor2))

[1 2 3 4 5 6 7]
[[-1. -1. -1.]
 [-1. -1. -1.]]


In [ ]:
tf.zeros([3, 4], tf.int32)  # [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
tf.ones([2, 3], tf.int32)  # [[1, 1, 1], [1, 1, 1]]


In [ ]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
tf.zeros_like(tensor)  # [[0, 0, 0], [0, 0, 0]]
tf.ones_like(tensor)  # [[1, 1, 1], [1, 1, 1]]

In [85]:
# Output tensor has shape [2, 3].
tensor = tf.fill([2, 3], 9) #==> [[9, 9, 9][9, 9, 9]]
sess.run(tensor)

array([[9, 9, 9],
       [9, 9, 9]], dtype=int32)

In [151]:
tf.reset_default_graph()
sess = tf.Session()

# Variable

### Call variable constructor

In [144]:

# Create a variable.
w = tf.Variable(3.0, name='v1')
init = tf.global_variables_initializer()

with sess.as_default():
    init.run()
    print(sess.run(w))

3.0


### Create variable

This creates a variable named "my_variable" which is a three-dimensional tensor with shape [1, 2, 3]. This variable will, by default, have the dtype tf.float32 and its initial value will be randomized via tf.glorot_uniform_initializer.TensorFlow provides many convenient initializers where you can reference TF documentation

In [153]:
my_variable = tf.get_variable("v2", [1, 2, 3])
my_variable

<tf.Variable 'v2:0' shape=(1, 2, 3) dtype=float32_ref>

## Collections and adding variables

In [146]:
tf.add_to_collection("my_collection_name", my_variable)

In [147]:
tf.get_collection("my_collection_name")

[<tf.Variable 'v2:0' shape=(1, 2, 3) dtype=float32_ref>]

### place variable on GPU device

In [138]:
#with tf.device("/device:GPU:1"):
#    v = tf.get_variable("v", [1])

### Assign a value to a variable

In [163]:
def initialize_variable(scope_name, var_name, shape):
    with tf.variable_scope(scope_name) as scope:
        v = tf.get_variable(var_name, shape)
        scope.reuse_variable()

def get_scope_variable(scope_name, var_name):
    with tf.variable_scope(scope_name, reuse=True):
        v = tf.get_variable(var_name)
    return v

In [172]:
assignment.shape

TensorShape([Dimension(1)])

In [183]:
#v3 = initialize_variable('foo','v3',[1])
v3 = get_scope_variable('foo','v3')
assignment = v3.assign_add([1])
init = tf.global_variables_initializer()
with sess.as_default():
    init.run()
    print(sess.run(assignment))

[ 0.93581343]


# Placeholders

In [ ]:
x = tf.placeholder(tf.float32, shape=(1024, 1024))
y = tf.matmul(x, x)

In [ ]:
with tf.Session() as sess:
    print(sess.run(y))  # ERROR: will fail because x was not fed.

In [ ]:
with tf.Session() as sess:
    rand_array = np.random.rand(1024, 1024)
    print(sess.run(y, feed_dict={x: rand_array}))  # Will succeed.