In [1]:
#!pip3 install tensorflow
import tensorflow as tf

# Tensor Video 2.3

# Tensor

In [2]:
a = tf.constant([[1.0, 2.0], [3.0, 4.0]])
a

<tf.Tensor 'Const:0' shape=(2, 2) dtype=float32>

In [3]:
sess = tf.Session()
sess.run(a)

array([[ 1.,  2.],
       [ 3.,  4.]], dtype=float32)

# Rank

In [4]:
#Rank of previous example
sess.run(tf.rank(a))

2

### Rank 0

In [5]:
mammal = tf.Variable("Elephant", tf.string)
ignition = tf.Variable(451, tf.int16)
floating = tf.Variable(3.14159265359, tf.float64)
its_complicated = tf.Variable((12.3, -4.85), tf.complex64)


In [6]:
sess.run(tf.rank(mammal))

0

For a rank 0 tensor (a scalar), no indices are necessary, since it is already a single number.

### Rank 1

In [7]:
mystr = tf.Variable(["Hello"], tf.string)
cool_numbers  = tf.Variable([3.14159, 2.71828], tf.float32)
first_primes = tf.Variable([2, 3, 5, 7, 11], tf.int32)
its_very_complicated = tf.Variable([(12.3, -4.85), (7.5, -6.23)], tf.complex64)

In [8]:
sess.run(tf.rank(first_primes))

1

### For a rank 1 tensor (a vector), passing a single index allows you to access a number:

In case of image processing

### Confusion with many aspirants while understanding rank

In [9]:
my_image = tf.zeros([10, 299, 299, 3])  # batch x height x width x color

# What should be the rank 1 or 4?

## Getting a tf.Tensor object's rank

In [10]:
r = tf.rank(my_image)
sess.run(r)

4

### using indexes

For a rank 0 tensor (a scalar), no indices are necessary, since it is already a single number.

For a rank 1 tensor (a vector), passing a single index allows you to access a number:


In [11]:
my_scalar = my_image[2,1]

In [12]:
my_scalar

<tf.Tensor 'strided_slice:0' shape=(299, 3) dtype=float32>

In [13]:
#For tensors of rank 2 or higher, the situation is more interesting. 
#For a tf.Tensor of rank 2, passing two numbers returns a scalar, as expected:

my_scalar = my_image[1, 2, 3,2]
print(my_scalar)

#Passing a single number, however, returns a subvector of a matrix, as follows:

my_row_vector = my_image[1,1,2]
print(my_row_vector)

##You might encounter the way of column slicing as below but avoid using it unless you are comfortable
my_column_vector = my_image[:, 298]
print(my_column_vector)

#The : notation is python slicing syntax for "leave this dimension alone". This is useful in higher-rank Tensors, 
#as it allows you to access its subvectors, submatrices, and even other subtensors.

Tensor("strided_slice_1:0", shape=(), dtype=float32)
Tensor("strided_slice_2:0", shape=(3,), dtype=float32)
Tensor("strided_slice_3:0", shape=(10, 299, 3), dtype=float32)


### Alternative specialized way to slicing

In [24]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]],
                 [[3, 3, 3], [4, 4, 4]],
                 [[5, 5, 5], [6, 6, 6]]])


In [25]:
sess.run(tf.slice(t,begin=[1,0,0],size=[1,2,2]))

array([[[3, 3],
        [4, 4]]], dtype=int32)

# Shape

In [26]:
rank_three_tensor = tf.ones([3, 4, 5])
matrix = tf.reshape(rank_three_tensor, [6, 10])  # Reshape existing content into
                                                 # a 6x10 matrix
matrixB = tf.reshape(matrix, [3, -1])  #  Reshape existing content into a 3x20
                                       # matrix. -1 tells reshape to calculate
                                       # the size of this dimension.
matrixAlt = tf.reshape(matrixB, [4, 3, -1])  # Reshape existing content into a
                                             #4x3x5 tensor

# Note that the number of elements of the reshaped Tensors has to match the
# original number of elements. Therefore, the following example generates an
# error because no possible value for the last dimension will match the number
# of elements.



In [27]:
#yet_another = tf.reshape(matrixAlt, [13, 2, -1])  # ERROR!

# Data types
### To inspect a tf.Tensor's data type use the Tensor.dtype property.

In [14]:
# Cast a constant integer tensor into floating point.
int_tensor = tf.constant([1, 2, 3], dtype=tf.int32)
print(int_tensor)
float_tensor = tf.cast(int_tensor, dtype=tf.float32)
print(float_tensor)

Tensor("Const_1:0", shape=(3,), dtype=int32)
Tensor("Cast:0", shape=(3,), dtype=float32)


# Tensorflow constants

In [4]:
# Constant 1-D Tensor populated with value list.
tensor1 = tf.constant([1, 2, 3, 4, 5, 6, 7]) #   [1 2 3 4 5 6 7]
print(sess.run(tensor1))
# Constant 2-D tensor populated with scalar value -1.
tensor2 = tf.constant(-1.0, shape=[2, 3]) # [[-1. -1. -1.],[-1. -1. -1.]]
print(sess.run(tensor2))

[1 2 3 4 5 6 7]
[[-1. -1. -1.]
 [-1. -1. -1.]]


In [4]:
tf.zeros([3, 4], tf.int32)  # [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
tf.ones([2, 3], tf.int32)  # [[1, 1, 1], [1, 1, 1]]


<tf.Tensor 'ones:0' shape=(2, 3) dtype=int32>

In [5]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
tf.zeros_like(tensor)  # [[0, 0, 0], [0, 0, 0]]
tf.ones_like(tensor)  # [[1, 1, 1], [1, 1, 1]]

<tf.Tensor 'ones_like:0' shape=(2, 3) dtype=int32>

In [6]:
# Output tensor has shape [2, 3].
tensor = tf.fill([2, 3], 9) #==> [[9, 9, 9][9, 9, 9]]
sess.run(tensor)

array([[9, 9, 9],
       [9, 9, 9]], dtype=int32)

In [3]:
tf.reset_default_graph()
sess = tf.Session()

# Variable

### Call variable constructor

In [7]:

# Create a variable.
w = tf.Variable(3.0, name='v1')  #tf.Variable(<initial-value>, name=<optional-name>)
init = tf.global_variables_initializer()

with sess.as_default():
    init.run()
    print(sess.run(w))

3.0


### Create variable

This creates a variable named "v2" which is a three-dimensional tensor with shape [1, 2, 3]. This variable will, by default, have the dtype tf.float32 and its initial value will be randomized via tf.glorot_uniform_initializer.TensorFlow provides many convenient initializers where you can reference TF documentation

In [10]:
my_variable = tf.get_variable("v2", [1, 2, 3])
my_variable

<tf.Variable 'v2:0' shape=(1, 2, 3) dtype=float32_ref>

## Collections and adding variables

In [13]:
tf.add_to_collection("my_collection_name", my_variable)

In [14]:
tf.get_collection("my_collection_name")

[<tf.Variable 'v2:0' shape=(1, 2, 3) dtype=float32_ref>,
 <tf.Variable 'v2:0' shape=(1, 2, 3) dtype=float32_ref>]

### place variable on GPU device

In [8]:
#with tf.device("/device:GPU:1"):
#    v = tf.get_variable("v", [1])

### Assign a value to a variable

In [15]:
def initialize_variable(scope_name, var_name, shape):
    with tf.variable_scope(scope_name) as scope:
        v = tf.get_variable(var_name, shape)
        scope.reuse_variables()  ### important

def get_scope_variable(scope_name, var_name):
    with tf.variable_scope(scope_name, reuse=True):
        v = tf.get_variable(var_name)
    return v

In [17]:
#v3 = initialize_variable('foo','v3',[1])
v3 = get_scope_variable('foo','v3')
assignment = v3.assign_add([2])
init = tf.global_variables_initializer()
with sess.as_default():
    init.run()
    print(sess.run(v3))
    print(sess.run(assignment))

[ 0.38126719]
[ 2.38126707]


In [18]:
assignment.shape

TensorShape([Dimension(1)])

# Placeholders

In [19]:
x = tf.placeholder(tf.float32, shape=(1024, 1024))
y = tf.matmul(x, x)

In [20]:
with tf.Session() as sess:
    print(sess.run(y))  # ERROR: will fail because x was not fed.

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [1024,1024]
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=[1024,1024], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'Placeholder', defined at:
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/interactiveshell.py", line 2683, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/interactiveshell.py", line 2787, in run_ast_nodes
    if self.run_code(code, result):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/interactiveshell.py", line 2847, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-19-7fc7b62dfe9f>", line 1, in <module>
    x = tf.placeholder(tf.float32, shape=(1024, 1024))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tensorflow/python/ops/array_ops.py", line 1599, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3091, in _placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [1024,1024]
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=[1024,1024], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]


In [22]:
import numpy as np
with tf.Session() as sess:
    rand_array = np.random.rand(1024, 1024)
    print(sess.run(y, feed_dict={x: rand_array}))  # Will succeed.

[[ 249.21287537  250.5213623   257.17016602 ...,  257.48718262
   254.22686768  245.65486145]
 [ 246.03964233  249.72166443  256.07592773 ...,  259.36190796
   255.15158081  246.28155518]
 [ 255.54675293  257.49642944  258.78335571 ...,  260.2729187   259.14285278
   247.52252197]
 ..., 
 [ 245.5398407   252.29200745  257.84191895 ...,  258.84661865
   255.88340759  241.67118835]
 [ 251.332901    250.97621155  253.9876709  ...,  257.53219604
   254.44239807  241.88392639]
 [ 246.86076355  246.87371826  249.67906189 ...,  251.81774902
   252.61724854  245.32392883]]
