In [43]:
import tensorflow as tf

In [44]:
sess = tf.Session()

## Common Math functions

In [45]:
a = tf.constant([[2,4],[3,6],[4,6]])
b = tf.constant([[6],[4]])

In [52]:
a.shape

TensorShape([Dimension(3), Dimension(2)])

In [53]:
b.shape

TensorShape([Dimension(2), Dimension(1)])

In [54]:
sess.run(tf.transpose(a))

array([[2, 3, 4],
       [4, 6, 6]], dtype=int32)

In [51]:
print(sess.run(tf.multiply(tf.transpose(a),b)))


[[12 18 24]
 [16 24 24]]


In [56]:
print(sess.run(tf.cumsum([1, 3, 2,5])))

[ 1  4  6 11]


In [57]:
print(sess.run(tf.negative(a)))

[[-2 -4]
 [-3 -6]
 [-4 -6]]


Tensorflow div operation returns the same type as the inputs

In [58]:
print(sess.run(tf.div(3,4)))
print(sess.run(tf.truediv(3,4)))  #casts integers into floats before dividing and always returning a float
print(sess.run(tf.floordiv(3.0,4.0)))  #return a float, but rounded down to the nearest integer

0
0.75
0.0


Tensorflow mod function returns the remainder after the division

In [59]:
print(sess.run(tf.mod(22.0, 5.0)))

2.0


Tensorflow cross function returns the cross-product between two tensors

In [7]:
print(sess.run(tf.cross([1., 0., 0.], [0., 1., 0.])))

#https://www.mathsisfun.com/algebra/vectors-cross-product.html

[ 0.  0.  1.]


## Build an equation

In [27]:
#Lets say we need to implement 3x^4 + 2x -5

In [60]:
def solve_equation(x):
    return tf.subtract(tf.add(3*tf.pow(x,4),2*x),5)

In [62]:
sess.run(solve_equation(1))

0

##  Broadcasting

In [63]:
a = tf.constant([[1, 2, 3], [4, 5, 6]], name='a')
b = tf.constant([100, 101, 102], name='b')
add_op = a + b

with tf.Session() as session:
    print(session.run(add_op))

[[101 103 105]
 [104 106 108]]
