In [1]:
import tensorflow as tf
sess = tf.Session()

# ReLU

In [2]:
print(sess.run(tf.nn.relu([-2., 7., 23.])))

[  0.   7.  23.]


# relu with min max

In [5]:
print(sess.run(tf.nn.relu6([-2., 2., 12.])))

[ 0.  2.  6.]


# sigmoid

In [6]:
print(sess.run(tf.nn.sigmoid([-1., 0., 1.])))

[ 0.26894143  0.5         0.7310586 ]


# tanh

In [7]:
print(sess.run(tf.nn.tanh([-1., 0., 1.])))

[-0.76159418  0.          0.76159418]
